nimblehq/rails-templates

rails_docker.rb
rails_docker/Dockerfile
rails_docker/application.yml
rails_docker/docker-compose.yml
rails_docker/test.sh

Fixes:
✅ Fix db creation issue. Currently the docker app cannot connect to the db container

Hotfix - Docker issue

---

lib/test_env.rb
rails_docker.rb
shared/rspec/support/disable_animation.rb

Tasks List:
✅  Added `Rack::NoAnimations` middleware in the test env.

Added disable animation Middleware to the test env

---

PULL_REQUEST_TEMPLATE.md

All pull requests are not created equally. But most need to contain a minimum of information. So a PR template will help in achieving that.
Docs: [help.github.com/articles/creating-a-pull-request-template-for-your-repository](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)

[CHORE] Add pull request template to streamline PRs

---

.github/PULL_REQUEST_TEMPLATE.md

Some English syntax issues and spelling mistakes were introduced in the rush of implementing this nice template. So it's time to fix those 🙌

Minor improvments to the PR template

---

rails_docker.rb
rails_docker/Dockerfile
rails_docker/Gemfile.txt

Just upgrading Ruby to 2.5.3
Upgrade docker and gemfile
Check code
Fixes #59

Upgrading Ruby

---

rails_docker/Gemfile.txt

Upgrading to rails 5.1.6
We need to upgrade as 5.1.4 doesn't support pg > 1.0
Simple change
Fixes #65

Upgrading Rails

---

rails_docker.rb
shared/app/assets/stylesheets/application.scss

✅ Initialize the assets directory
Setup the js and css directory following the structure in our compass 
After creating the project from the template the asset directory looks like this

Initialize assets folder structure

---

rails_docker.rb

✅ Add more files to gitignore
Some files are not added to gitignore, so we add it manually when creating the project. Here I add it to the template

Setup gitignore

---

.semaphore/semaphore.yml
bin/wait_for.sh
makefile
rails_docker.rb
shared/README.md

Fixes #76 
This introduces basic semaphore setup
I've added a `makefile` that runs through the steps involved testing the template.

Setup a test pipeline to test every pull request 

---

rails_docker/Dockerfile

Fixes #117
Revert to Ruby Slim image. 
Just revert the changes from the PR #106 
1/ Build success 
2/ Can run the test inside the Docker container

[#117] Revert to Ruby Slim image

---

rails_docker.rb
shared/.npmrc
shared/app/assets/stylesheets/functions/_sizing.scss
shared/linters/.eslintignore
shared/linters/.eslintrc

Add **@nimbl3/eslint-config-nimbl3** to **package.json**
We have ESlinter configuration in **shared/linters** but we didn't add the **@nimbl3/eslint-config-nimbl3** to **package.json**
1/ package.json
2/ **nimble-eslint** is installed automatically

Add the @nimbl3/eslint-config-nimbl3 to package.json file

---

rails_docker/Dockerfile
rails_docker/Gemfile.txt

Upgrade to Rails 6.0.1
Just change the **Gemfile.txt**  😺 
Tested on my local ✅

Upgrade to Rails 6.0.1

---

shared/app/controllers/concerns/localization.rb

Just adding the default_url_options method as we need to add that method manually in each project

Adding default_url_options

---

template.rb
variants/api/app/controllers/concerns/localization.rb
variants/api/app/template.rb
variants/api/template.rb

✅ Create the api variant
- Setup localization from the `Accept-Language` header
Spec should pass 🌲

Create api variant

---

README.md

✅ Update the `README`
Please check -> https://github.com/nimblehq/rails-templates/blob/chore/readme/README.md

Add `how to contribute` section to README file

---

shared/rspec/codebase/codebase_spec.rb

Reverts nimblehq/rails-templates#144
This is merged to the wrong branch. Let's reopen the pr for the next version 😭

Revert "Check exit status code rather than stdout message"

---

.template/addons/docker/Dockerfile.tt

- Refactor instructions in Dockerfile
Fix nimblehq/rails-templates#172
Some commands could be grouped/removed to reduce the layers.
- Group ENV instructions
- Group the package installations
- Remove mkdir "$APP_HOME" (It automatically creates when we specify WORKDIR)
For `yarn install`, it could be removed because it is run when assets are precompiled. But I keep it as is because it easier to understand.
Dockerfile for web app (20 Build steps)
```
FROM ruby:2.6.5-slim
ARG BUILD_ENV=development
ARG RUBY_ENV=development
ARG NODE_ENV=development
ARG ASSET_HOST=http://localhost
ENV BUILD_ENV=$BUILD_ENV \
RACK_ENV=$RUBY_ENV \
RAILS_ENV=$RUBY_ENV \
NODE_ENV=$NODE_ENV \
ASSET_HOST=$ASSET_HOST \
APP_HOME=/test_app \
PORT=80 \
BUNDLE_JOBS=4 \
BUNDLE_PATH="/bundle" \
NODE_VERSION="12" \ …
```

Optimize Dockerfile

---

.semaphore/semaphore.yml

✅ Integrate with semaphore 2
Setup the pipeline on Semaphore 2.0 to test the template.

Integrate with Semaphore 2

---

template.rb

Resolved #214 
Just override the default .ruby-version file
1/ Already tested on my local
2/ The test should be passed

Forcing the ruby template version

---

spec/codebase/codebase_spec.rb

Resolve #204
The codebase specs should be passed
The test speed is increasing a bit on Semaphore 😁 
Before
After

Enable --parallel on rubocop

---

.template/variants/web/Gemfile.rb

Resolved #176
Just upgrade Webpacker to the latest version
Before
After

Upgrade Webpacker

---

.template/spec/variants/web/app/template_spec.rb
.template/variants/web/app/template.rb

Resolve #200
Enable core-js by adding it to the main entry point (packs/application.js)
The test should be passed

Enable core-js

---

.template/addons/docker/docker-compose.test.yml.tt
Dangerfile
Gemfile.tt
spec/support/simplecov.rb

- Use `danger-simplecov_json` to report the test suite code coverage
- Addresses issue https://github.com/nimblehq/rails-templates/issues/221
- Used in The 1 project

Integrate danger-simplecov_json

---

.template/addons/nginx/bin/start.sh
.template/addons/nginx/config/nginx/app.conf.template.tt
.template/spec/addons/base/nginx/template_spec.rb

Solved https://github.com/nimblehq/rails-templates/issues/259
1/ The changes and the test is passed
2/ 
3/ This implementation has bene applied in [loyalty-demo-web](https://github.com/nimblehq/loyalty-demo-web/pull/29/files)

Allow Nginx handle incoming HTTP request on Heroku

---

.template/addons/heroku/Dockerfile.worker.tt
.template/spec/base/bin/template_spec.rb
bin/template.rb
bin/worker.sh

Solved https://github.com/nimblehq/rails-templates/issues/260
1/ Adding worker.sh file
2/ Set `./bin/worker.sh` as the cmd for Docker.worker file
The test is passed

Adding worker.sh

---

README.md.tt

Solved https://github.com/nimblehq/rails-templates/issues/257
Adding `./bin/docker-prepare` into README

Adding `./bin/docker-prepare` into README

---

.template/addons/github/.github/workflows/README.md.tt
README.md.tt

[#293 Update readme for heroku deploy](https://github.com/nimblehq/rails-templates/issues/293)
Update the `.github/workflows/readme.md` to include instructions for deploying to heroku and on how to setup the app on heroku.
Only md readme file updated, you can test the guide by:
- Read and challenge if it's easy to understand and if the level of abstraction is adapted (too much details? not enough?)
- Challenge from what you have done in previous projects
- Try to reproduce it with a new project

[#293] Update readme for heroku deploy

---

.template/addons/slim/Dangerfile.rb
.template/spec/variants/web/dangerfile_spec.rb
.template/spec/variants/web/gemfile_spec.rb
.template/spec/variants/web/spec/codebase/codebase_spec.rb
.template/variants/web/.stylelintignore
.template/variants/web/Dangerfile.rb
.template/variants/web/Gemfile.rb

Close https://github.com/nimblehq/rails-templates/issues/323
- Add Danger Stylelint 
- Integrate with our new [Danger Stylelint](https://github.com/nimblehq/danger-stylelint) on `web` variant.
Tested on a new project and it's working:

Report Stylelint errors on the PR

---

.template/addons/hotwire/Gemfile.rb
.template/addons/hotwire/template.rb
.template/variants/web/Gemfile.rb
template.rb

#332 
It prompt us to enable hotwire in newly generating rails application, if the answer is `Y` then it will add
- turbo-rails
- stimulus-rails
and enable them in the rails project.

feat(#332): ability to enable hotwire

---

.template/addons/github/.github/workflows/test.yml.tt
.template/addons/semaphore/.semaphore/semaphore.yml.tt

- Close #374
Verified on one of our Internal Rails projects

[gh374] Print Rspec output log in  format on CI

---

.template/addons/devise/spec_support.rb
.template/variants/web/spec/support/assets.rb

closes https://github.com/nimblehq/rails-templates/issues/395
- Load the Devise helper for request test(used in a client project)
- Precompile the assert for request test (used in a client project)
On the file changed tab

[gh395] Support request test

---

template.rb

close #409
Upgrade the version of Postgres to 15.2
`n/a`
| Updated version in Dockerfile                                                                              	|
|------------------------------------------------------------------------------------------------------------	|
| ![image](https://github.com/nimblehq/rails-templates/assets/63148598/b4c3294e-2932-4c5a-81c1-b555b7b001bd) 	|
| Generated the project successfully                                                                                                      	|
|-----------------------------------------------------------------------------------------------------------------------------------------	|
| ![Generated the project successfully](https://github.com/nimblehq/rails-templates/assets/63148598/9da084c3-7512-488e-abf6-3 …

[#409] Upgrate Postges to 15.2

---

.github/workflows/test_generated_app.yml
.github/workflows/test_production_build.yml
Gemfile.tt
README.md

Upgrade Rails to 7.0.6
This is the part 1 in the upgrade series, the next PR will be about Ruby upgrade 
The CI is passed

[#383] Upgrade Rails version

---

.template/spec/variants/web/app/template_spec.rb
.template/variants/web/app/template.rb

close #433 
Just create the `.keep` file
The CI is passed
Tested on local by generate the new project

[#433] Add the `.keep` file

---

.template/variants/web/.stylelintignore

Update .gitgnore file to ignore the public directory
Close #430 
`N/A`
`N/A`

[#430] Update the .stylelintignore - Add public/*

---

.template/variants/web/.gitignore.rb
README.md.tt

[@5.10.0](https://github.com/nimblehq/rails-templates/milestone/20?closed=1)
`n/a`
* Update README regarding copying the .env file by @tyrro in https://github.com/nimblehq/rails-templates/pull/475
`n/a`
**Full Changelog**: https://github.com/nimblehq/rails-templates/compare/5.9.0...5.10.0

Release 5.10.0

---

rubocop/custom_cops/required_inverse_of_relations.rb

2 PRs were merged without prior rebase, so the Cop from #500 and #495 conflicted.
`n/a`
Test should pass :white_check_mark:

Fix Rubocop issue after merging 2 PR

---

.template/addons/crud/lib/templates/slim/scaffold/_form.html.slim.tt
.template/addons/crud/lib/templates/slim/scaffold/edit.html.slim.tt
.template/addons/crud/lib/templates/slim/scaffold/new.html.slim.tt
.template/variants/web/app/template.rb

- Close #493 
This PR only focuses on the new, edit, and form view templates
https://github.com/nimblehq/rails-templates/assets/36690900/acae140e-1e35-4055-94d3-d63817ac3740

[#493][CRUD] Add the form view templates to the generator

---

.template/spec/base/config/environments/development_spec.rb
.template/spec/base/config/environments/production_spec.rb
.template/spec/base/config/environments/test_spec.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb

- Close #460
Add the default values for some environment variables to reduce the probability missing them while deploying the application, and can be modified when needed. 🚀 
`n/a`
Simple files changed. 💭

[#460] Revisit and set the default value for some environment variables

---

.rubocop.yml
.template/addons/custom_cops/template.rb
.template/spec/base/config/environments/development_spec.rb
.template/spec/base/config/environments/production_spec.rb
.template/spec/base/config/environments/test_spec.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
rubocop/custom_cops/class_template.rb
rubocop/custom_cops/class_template/expression_category.rb
rubocop/spec/class_template/expression_category_spec.rb
rubocop/spec/class_template_spec.rb
rubocop/spec/required_inverse_of_relations_spec.rb

[@1.15.0](https://github.com/nimblehq/rails-templates/pulls?q=is%3Apr+milestone%3A5.15.0+)
* [#499] Create a Rubocop cop for ordering instructions in class (e.g. Models) by @Goose97 in https://github.com/nimblehq/rails-templates/pull/509
* [#460] Revisit and set the default value for some environment variables by @sanG-github in https://github.com/nimblehq/rails-templates/pull/511
`n/a`
**Full Changelog**: https://github.com/nimblehq/rails-templates/compare/5.14.0...5.15.0

Release - 5.15.0
