nimblehq/rails-templates

shared/linters/config.reek

In Braive, we have many usage of the pattern where we set the instance through `before_action` like this https://github.com/troessner/reek/issues/1133, which the error should not be raised. 
And also in controllers, there might be many used of the instance variables. It might be good if we disable it.

Disable instance variable assumption detector for controllers

---

shared/rspec/support/sidekiq.rb

Sidekiq was added into the base template #38 but it's missing the default rspec config we usually use

Add missing rspec config for Sidekiq

---

.github/PULL_REQUEST_TEMPLATE.md

The PR template contained links for another project so needed to be modified.

[CHORE] Migrate the PR template to subdirectory .github

---

rails_docker/Dockerfile
shared/rspec/support/capybara.rb

Since tests are run inside a Docker container via `docker-compose.test.yml`, Google Chrome needs to be added to be able to run system specs.

Add Chrome Headless for system specs

---

rails_docker/docker-compose.dev.yml
rails_docker/docker-compose.test.yml
rails_docker/docker-compose.yml

In order for port mapping to work, it needs both the local port and the external ports to which other external services can connect too. The current mapping only include the external port 😔
Official doc: https://docs.docker.com/compose/compose-file/#ports
Before with incorrect port:
After:

Fix: Incomplete port mapping for all Docker Compose services

---

shared/rspec/rails_helper.rb

We should set it to `true` because of use in System test.

Update transactional fixtures for using in system test

---

shared/rspec/support/simplecov.rb

Got some deprecated code warning in `simplecov` file.
```
/spec/support/simplecov.rb:2:in<top (required)>': [DEPRECATION] ::[] is deprecated.
```
Following this referrence.
https://github.com/colszowka/simplecov#using-multiple-formatters
[#35]

Fix: Deprecated code for simplecov

---

rails_docker/docker-compose.test.yml

- Right now we mostly don't use docker on local machine, for both development and testing. Docker is only used on testing on CI and sometime for production.
- Sometime environment on docker is different than on non-docker, even for local machine. This may cause some test failing on docker, while still passing on non-docker environment. It's a tough problem to debug, especially if the one failing is a system spec (we can only see the screen shots but not the chrome process). This PR makes the docker environment share the log folder with the host machine, to make easier it for debugging.

Access log file on docker test environment

---

rails_docker.rb

ISSUE: #64, #66 
This PR fix when generating the template using URL. It shows the error that cannot that cannot find files that required in `rails-docker.rb` because template generator will use URL as path in `require_relative` so it won't work.
Solved by using `apply` instead of `require_relative` that work with `source_path` that we added and both `apply`, `source_path` is provided by `Thor`. 
Also, fix `.env` file name that breaks the when generating application from template.
[Here is refrence](https://edgeguides.rubyonrails.org/rails_application_templates.html#advanced-usage) for how `apply` and `source_path` work.
Using this command `rails new rails-test -m https://raw.githubusercontent.com/nimbl3/rails-templates/bug/fix-require-from-url/rails_docker.rb -T` to generate rails …

Fix generating the template with URL is NOT working.

---

rails_docker/docker-compose.test.yml

ISSUE #71 
We don't need to mapping port when using docker-compose on test environment on Semaphore CI.
- Remove the mapping port.
- Add the Redis settings. 
The docker-compose on test environment should run without the error on Semaphore CI.

Remove the mapping port on docker-compose on test environment.

---

shared/rspec/support/disable_animation.rb

Fixes #69
The codebase spec will fail because we are missing the RuboCop disabled comments on `disabled_animation.rb` file.
In this PR, I fix 2 things.
1. Add RuboCop disabled comments after the `inject()` method.
2. Enter a new line after guard clause in `call()` method. (Fix RuboCop `Layout/EmptyLineAfterGuardClause` Rule).
RuboCop should valid on the `disabled_animation.rb` file.

Fix missing RuboCop disabled comments in disabled animation file.

---

rails_docker/docker-compose.dev.yml
rails_docker/docker-compose.yml

Fixes #67 
As a description in #67, We can NOT run the `Procfile.dev` file because we are missing the Redis configuration in the Docker compose.
Just as Redis configuration to the Docker compose file. 
You should start the Redis with `Procfile.dev` file

Fix missing Redis configuration on Docker compose file. 

---

shared/rspec/support/capybara.rb

Set `wait_on_first_by_default` in Capybara configuration to true because when we use first method in Capybara it won't wait for element to render completely if we chain with click method it will click immediately sometimes it cause test to fail, by adding this configuration will make Capybara wait until the first element appear then invoke chain method. 
-- Work in progress --

Set wait_on_first_by_default to true

---

rails_docker/Dockerfile

I used our Dockeflie template to build the Overblock image and I think we can improve it a bit on Production mode
+ Don't set up Google Chrome on Production mode
+ Don't bundle the `development` gems and add the `--deployment` flag on Production mode
+ [--deployment flag documentation](https://bundler.io/bundle_install.html#bundle-install)
> The --deployment flag activates a number of deployment- and CI-friendly conventions:
> 
> - Isolate all gems into vendor/bundle (equivalent to --path vendor/bundle)
> - Require an up-to-date Gemfile.lock (equivalent to --frozen)
> - Disable ANSI color output
> - If bundle package was run, do not fetch gems from rubygems.org. Instead, only use gems in the checked in vendor/cache
+ Mina also use the `--deployment` flag when they run bundle on Production …

Improve the Dockerfile on Production mode

---

README.md
rails_docker.rb
rails_docker/Gemfile.txt
shared/app/assets/javascripts/application.js

✅ Upgrade Rails to 5.2.3
Upgrading rails and add some libraries that is missing + new from rails 5.2
New gems: 💎 
- bootsnap
- chromedriver-helper
New configuration files: 📁 
- /config/credentials.yml.enc (A replacement for secret.yml)
- /config/master.key
- /config/initializers/content_security_policy.rb
- /config/storage.yml
1. Create the project from the template
2. Start the rails app with
```
bin/envsetup
foreman start -f Procfile.dev
```

Update Rails from 5.1.6 to 5.2.3

---

rails_docker.rb
rails_docker/Dockerfile

✅ Add missing gnupg package in the dockerfile
✅ Fix bundle error when building the image
There is an error while installing yarn when building the docker image regarding the missing package.
When running bundle install, the bundler version should match the version specified in the gemfile.lock. The version in gemfile.lock is actually comes from local when we new rails project from the template.
**UPDATED** ☝️ We're agreed to use the bundle version that built in with the ruby. 
- For ruby 2.5.3 - Bundler version - 1.17.3
- For ruby 2.6.2 - Bundler version - 1.17.2
Before, there is an env variable that we can set on ruby image - `BUNDLER_VERSION`. But it is removed - https://github.com/docker-library/ruby/pull/255. 
There might be errors on this step if your local bundler is in a different …

Fix errors when building the docker image

---

README.md
rails_docker.rb
rails_docker/Dockerfile
rails_docker/Gemfile.txt

✅ Update ruby version to 2.6.2
Update ruby docker image and update the version the Gemfile and .ruby-version
https://www.ruby-lang.org/en/news/2018/12/25/ruby-2-6-0-released/

Update ruby version from 2.5.3 to 2.6.2

---

shared/config/application.yml
shared/config/database.yml

✅ Update database configurations
When running `rake db:setup` on local, it should create 2 databases for development and test. Currently it create only one.
The problem is in our env, we set
```
development:
<<: *default
DB_NAME: "#{app_name}_development"
test:
<<: *default
DB_NAME: "#{app_name}_test"
```
So when we run `rake db:setup` on local, it always get the `<name>_development` because we're on the development.
To fix, I move the suffix to `database.yml` instead.
After:

Update database config

---

rails_docker/docker-compose.yml
shared/config/application.yml

✅ Remove secret key base from env
Since Rails 5.2, the secret is changed. Right now if we create a new application, the secret key base is set in `config/credentials.yml.enc` where content is encrypted with the `master.key`.
The `credentials.yml.enc`
The initial content that comes with rails
To view/edit the credentials
```
EDITOR="<editor_cli> --wait" rails credentails:edit
EDITOR="code --wait" rails credentails:edit
```
To view/edit, it needs the `config/master.key` to decrypt the file. This file is not committed to the repository and should be kept+managed by ourself.
For production, we can place that key on the server or set by environment `RAILS_MASTER_KEY`.
To access the credentials in the code we can do
```
Rails.application.credentials.secret_key_base
```
More info on credentails: …

Update secret key base configuration due to rails 5.2 changes

---

rails_docker.rb

✅ Add Rack deflater to compress responses
To resolve Issue #85 ⚒ 
https://thoughtbot.com/blog/content-compression-with-rack-deflater 
The configuration added to `config/application.rb`
The page size get reduced 😮 (This is the default rails page)
Without deflater:
With deflater:

Add Rack Deflater to reduce response size

---

lib/bullet.rb
rails_docker.rb
shared/rspec/support/bullet.rb

✅ Add Bullet Configurations for `development` and `test`
Bullet gem is installed but it is not configured. (Issue #20 - Change default configs in test env)
Here I added configurations for development and test. I get the configurations from vcliq project.
The warning is shown at the bottom of the screen
The test will failed if there is n+1 queries
After fixing the issue, the test is passed

Enable Bullet to watch for N+1 queries

---

rails_docker.rb
shared/.editorconfig

✅ Setup editorconfig files
Add a editorconfig file to maintain the consistent code style across various IDEs like we did in MIA.

Setup editorconfig

---

rails_docker/Dockerfile
rails_docker/Gemfile.txt
shared/rspec/support/webdrivers.rb

✅ Replace `chromedriver-helper` with `webdrivers`
Now `chromedriver-helper` is deprecated and it is moved to `webdrivers`. On new Rails 6, it has been moved to `webdrivers` too. See https://github.com/rails/rails/pull/35732
I know we haven't include the chromedriver-helper in our gemfile before. But maybe we should? So that we don't need to install `chromedriver` on each machine that we've been working on.
The system test is still runnable.
To update, we can set the version in `support/webdrivers.rb`
```
Webdrivers::Chromedriver.version = '2.46'
```
The webdriver is installed at `~/.webdriver` by default. After update the version in the config and run the spec again, it should update the installed binary.

Replace chromedriver-helper with webdrivers

---

rails_docker/Dockerfile

✅ Fix chrome installation script
I think this is added to resolve this error
```
WARNING: The following packages cannot be authenticated!
google-chrome-stable
E: There are problems and -y was used without --force-yes
ERROR: Service 'test' failed to build: The command '/bin/sh -c apt-get update -qq &&     apt-get install -y --no-install-recommends build-essential libpq-dev nodejs yarn google-chrome-stable &&     apt-get install -y --no-install-recommends rsync locales chrpath pkg-config libfreetype6 libfontconfig1 git cmake wget unzip &&     apt-get clean &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```
@Lahphim and @Yutna face this issue sometimes. I tried to fix the chrome installation without the key by installing chromium or installing another chrome package.
- …

Update chrome install script

---

rails_docker.rb
rails_docker/Dockerfile
rails_docker/Gemfile.txt
shared/rspec/support/assets.rb

Do not fallback to the Sprockets server when the precompiled asset is missing on test ENV
When we use the `image_tag` sometimes we forgot to put the `image extension` like `= image_tag 'logo'` (the correct one should be `= image_tag 'logo.png'`). With that, on the Development and Test ENV everything works (because it fallback to the Sprockets server to get the assets), but when we deploy to Production, it returns a 500 error, technically it shouldn't be like that, it should fail on Test ENV first.
https://stackoverflow.com/questions/29409959/rails-assets-not-precompiling-in-production

Do not fallback to the Sprockets server when the precompiled asset is missing on Test env

---

shared/rspec/support/sidekiq.rb

Removed the `Sidekiq::Testing.fake!` line from the sidekiq testing  config file as `fake` testing mode is sidekiq's default testing mode and it should be enabled without explicitly defined it.
Requiring ` 'sidekiq/testing'` will automatically call `Sidekiq::Testing.fake!`. 
From sidekiq testing wiki [page](https://github.com/mperham/sidekiq/wiki/Testing) 
N/A

Remove sidekiq default fake mode for testing line

---

rails_docker/Gemfile.txt
shared/linters/.rubocop.yml
shared/rspec/rails_helper.rb
shared/rspec/support/assets.rb
shared/rspec/support/capybara.rb

Update rubocop and fix some warnings
- Rails cops were removed from [0.72](https://github.com/rubocop-hq/rubocop/blob/master/CHANGELOG.md#changes-6), so need to add manually
- Style::FormatStringToken` `EnforcedStyle` default is `annotated`, change to `template` as we prefer `format('%{greeting}', greeting: 'Hello')` than `format('%<greeting>s', greeting: 'Hello')`
No more warnings from rubocop

Update rubocop.yml and add rubocop-rails

---

rails_docker/Gemfile.txt

With currently setup for debugging we can not make step by step debugging as well as navigation between stack.
Refer this [cheatsheet](https://gist.github.com/palkan/d89757a90cfbeb047c63#debugging-with-pry-byebug) and [pry-byebug](https://github.com/deivid-rodriguez/pry-byebug) for documentation.

Add pry-byebug gem for step by step debugging and stack navigation

---

shared/rspec/codebase/codebase_spec.rb

In the codebase test, we are checking the output of command. For example `expect(`rubocop --format simple`).to include 'no offenses detected'`. Output message are not standard and I think they can change often, whereas exit status code command line applications are standard, and we can be sure that exit status `0` means success.
https://www.rubydoc.info/gems/rubocop/0.37.2#Exit_codes
https://apidock.com/ruby/Kernel/system
Tested it  for projects using this template.

Check exit status code rather than stdout message

---

shared/rspec/support/webdrivers.rb

Remove the default version configuration for Chrome Driver
The webdriver will use the [latest stable version as default](https://github.com/titusfortner/webdrivers#version-pinning)

Use the latest stable web driver version for Selenium as default

---

lib/config.rb
rails_docker.rb

✅ Bring back some missing configurations
There are some missing configurations but the script is passed because it is just the warnings from Thor.
I'm just fixing it for now. Later we can add more tests to catch these cases.
Final files:
1. `application.rb`
2. `development.rb`

Add missing configurations

---

rails_docker/docker-compose.dev.yml.tt
rails_docker/docker-compose.test.yml.tt
rails_docker/docker-compose.yml.tt
shared/config/application.yml.tt
shared/config/database.yml

- Upgrade Postgresql image to 12.1
- Upgrade Redis to 5.0.7
- Minor improvement the DB configuration, changing the USERNAME to **DB_USERNAME**
As the current Postgresql and Redis version is too old in this template, we should upgrade it to the latest version
Heroku also supports PostgreSQL 12 and Redis 5 by default already.
- https://devcenter.heroku.com/articles/heroku-postgresql
- https://devcenter.heroku.com/articles/heroku-redis

Upgrade Postgresql redis image

---

spec/codebase/codebase_spec.rb

- We faced the problem in one project as everything works well on `development` environment, but when we deploy to UAT (production mode) it failed.
```ruby
`/bundle/ruby/2.6.0/gems/zeitwerk-2.2.1/lib/zeitwerk/loader.rb:351:in const_get': uninitialized constant ... (NameError)
```
- Rails 6 is using zeitwerk loader as default, In this PR, I added `zeitwerk` loading checking to our codebase spec to make sure our code will be works on development as well as production.
```
bundle exec rake zeitwerk:check
```
N/A
- Should pass all tests

Add zeitwerk checking to codebase spec

---

.template/addons/docker/.dockerignore.tt
template.rb

✅ Add the pull request template for github
Fix nimblehq/rails-templates#173
We already have the `.github` template on this repo, so we can just simply copy the directory there.
The file is generated on a generated rails app
For the testing part, we cannot test with serverspec as it won't create this file in the docker container.

Add Github PR template

---

.template/addons/docker/template.rb
.template/addons/semaphore/template.rb
.template/spec/base/config/environments/development_spec.rb
.template/spec/base/config/environments/production_spec.rb
.template/spec/base/config/environments/test_spec.rb
.template/variants/api/template.rb
.template/variants/web/Gemfile.rb
.template/variants/web/app/template.rb
.template/variants/web/template.rb
README.md
template.rb

- Allow to apply single addon onto an existing application
The path needs to be fixed to make it work remotely.
To apply a single template, we need to call it through the main template as the repo needs to be cloned before it is templating.
```
rails app:template LOCATION=<template_url> ADDON=<addon name>
```
For an api application, there are no option provided like rails new command. So instead, you can pass `API` variable.
```
rails app:template LOCATION=<template_url> API=true
```
You can try create/update the application with the template on this branch
```
rails new <app_name> -m https://raw.githubusercontent.com/nimblehq/rails-templates/feature/apply-single-template/template.rb
rails app:template LOCATION=https://raw.githubusercontent.com/nimblehq/rails-templates/feature/apply-single …
```

Enable single template application

---

.template/lib/template/errors.rb
.template/variants/web/app/template.rb
.template/variants/web/template.rb
template.rb

✅ There are some issue for apply the template on existing application that the javascripts structure might be different or it is using the slim template
To fix, now I just displaying list of the errors, so that we know where should we fix.
I checked for the old application There are 2 problems I found:
1. Javascript structure
The old project might have the javascript on `/app/assets/javascripts`, the new one is on `app/javascripts`
2. Html template
The new project is init with the `erb`, the old one, usually in the `slim`. So there will be small problem on applying the template. (But very small as those project should have it set already)
So in these case, the errors will be displayed and we need to work on it manually.
Try apply with
```
rails app:template …
```

Add support old applications to apply the template

---

.template/addons/docker/.dockerignore.tt
.template/addons/docker/Dockerfile.tt
.template/addons/semaphore/.semaphore/promotion-production.yml.tt
.template/addons/semaphore/.semaphore/promotion-staging.yml.tt
.template/addons/semaphore/.semaphore/semaphore.yml.tt
.template/spec/base/bin/template_spec.rb
bin/docker-prepare
bin/template.rb
makefile

✅ Add the script to copy all app + engines dependencies for building docker image
There is an issue that Heroku has the limitation for deploying the container that the image should have less than 40 layers.
This could happen on any app, especially the one with lots of engines, because each engine would need at least 2 layers in order to bundle.
```
COPY engines/mia_website/lib/ ./engines/mia_website/lib/
COPY engines/mia_website/Gemfile engines/mia_website/mia_website.gemspec ./engines/mia_website/
```
To fix we add a script to prepare all the gemfiles on the app itself and also on all the engines before building the image. And during the build process, we just copy the directory into the image. So we could reduce a lot of layers for the app with many engines.
Test should pass 💚

Add script to copy the gem dependencies for building docker image

---

.template/spec/variants/web/package_json_spec.rb
.template/variants/web/.eslintrc
.template/variants/web/package.json.rb

Update the link to ESLint shared library from `nimbl3` to `nimblehq` NPMJS organization.
Linked PR on the ESLint repository: https://github.com/nimblehq/eslint-config-nimble/pull/6 
`N/A`

Replace link to shared ESLint with the new NPMJS organization

---

.template/addons/docker/Dockerfile.tt

Describe the big picture of your changes here to communicate to the team why we should accept this pull request. 
- Change the way to config bundler as `bundler 2.1` has changed their configuration command
Describe in detail how to test the changes. Referenced documentations are welcome as well.
- https://github.com/rubygems/bundler/releases/tag/v2.1.4
Show us the implementation: screenshots, gifs, etc.

[Chore] Fix bundler#v2.1 deprecated messages for --deployment, --path, --without

---

.rubocop.yml
.semaphore/semaphore.yml
.template/Gemfile.lock
Gemfile.tt
README.md
template.rb

- Upgrade Ruby to the latest stable version (2.7.1)
- Upgrade Rails to the latest stable version (6.0.3.2)
- Fix `.rubocop.yml`
- Upgrade bundler version
- Modify `.rubocop.yml` with new `TargetRubyVersion` and enable all `NewCops` 
- Run `bundler update` in `.template` folder

Upgrade to Ruby 2.7.1 and Rails 6.0.3.2

---

.template/variants/web/spec/support/webpack.rb

Prepare webpack assets only if there is at least one system test is executed
Just change to use `when_first_matching_example_defined` config
- Run normal tests (not type: :system) faster without webpack compilation
- The webpack compilation should be run once before running system tests

Prepare webpack assets only if there is at least one system test

---

.template/addons/docker/Dockerfile.tt

- There are some ENVs should only exist in build time, not in Docker container, so it should be declared by `ARG` instead of `ENV`
- Group `<%- if WEB_VARIANT -%>` check for better readability 
Describe in detail how to test the changes. Referenced documentations are welcome as well.
- https://vsupalov.com/docker-arg-vs-env/
- All tests should pass 🍏

[CHORE] Refactor Dockerfile template

---

.template/variants/web/spec/support/disable_animation.rb

Fixing rubocop issue in disable_animation.rb
Just following https://github.com/nimblehq/rails-templates/pull/195/files#diff-ff1a9ebbc2b786f43d96a4aab0a88c0eR55
Before
After
The test should passed ✅ ✅ ✅

Fixing rubocop issue in disable_animation.rb

---

spec/codebase/codebase_spec.rb
spec/template.rb

Resolve #203 
Just adding a piece code that validates the engine prefix names (that worked in The1 project)

Adding Engine prefix name validator

---

spec/template.rb

Resolve #211
Just remove the file because the `directory 'spec', force: true` copied the whole rspec folder

Remove the spec/template.rb in the new app

---

Gemfile.tt

Resolve #192
Just moving the `rspec-rails` to development group so the generate will work on development
https://github.com/rspec/rspec-rails#installation

Moving rspec-rails to development and test group

---

.rubocop.yml
spec/support/vcr.rb

- When I start using this template, run test failed
- And when run `rubocop` command after `docker-prepare` things broken.
- Update rubocop config to ignore tmp folder
- Combine loops in `vcr.rb` file according to rubocop error
- When initialize a new app using this template, test will pass when you `run test`
- After `docker-prepare`, everything should work fine when you run `rubocop` command

Fix Rubocop offense when first use template

---

.template/addons/docker/Dockerfile.tt

We didn't set `BUNDLE_PATH` environment variable in Dockerfile, then when starting the app, it raised the following error:
Just move the `BUNDLE_PATH ` and `BUNDLE_JOBS` to ENV section
The error shouldn't happen again

Fix missing gems when running app with docker

---

.reek.yml

Just removing the redundant IrresponsibleModule smells in the Reek config file
In the Reek configuration file, we already disable the IrresponsibleModule under the Detectors configuration so disable it again under directories configurations is redundant. This PR simply remove them.
```yml
detectors:
IrresponsibleModule:
enabled: false
directories:
"app/controllers":
IrresponsibleModule:
enabled: false
...
"app/helpers":
IrresponsibleModule:
enabled: false
...
```
Tests still passed

Remove redundant IrresponsibleModule smell in Reek config

---

template.rb

Fix error when applying an addon to existing project
- When applying github addon, it didn't work. The reason is `File.exist?(addon_template_path)` didn't find the file because it checked the file on the current working dir (the current project that running the script). Use `File.expand_path` with `template_root` parameter to get the file absolute path of the current file on template
- Tests should be passed
- You can add the github actions workflows to existing projects by applying the github addon:
`rails app:template LOCATION=https://raw.githubusercontent.com/nimblehq/rails-templates/bug/unable-to-apply-addon/template.rb ADDON=docker`

Fix error when applying an addon to existing project

---

.template/addons/docker/Dockerfile.tt
bin/docker-assets-precompile
bin/template.rb
config/application.yml.tt

✅ Add precompile assets script
In order to precompile the assets inside the docker image, we need to have all variables set to make the app successfully initializes. This is because we always use ENV.fetch to get the environment variables to fast-failing when the env is not set properly. 
To fix, we add the docker precompile assets script. Which will take all variables needed and set the dummy values. So all variables is available for the app to initialize.
- Spec should passed 🍏
- We can run the docker-compose build successfully

Add precompiling assets script to fix docker build

---

.rubocop.yml
Gemfile.tt
spec/codebase/codebase_spec.rb

Solved https://github.com/nimblehq/rails-templates/issues/124
1/ Adding [rubocop-rspec](https://github.com/rubocop-hq/rubocop-rspec)
2/ Modify some Rubocop Rspec rule
- [RSpec/HookArgument](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/HookArgument): Prefer to keep the `each` argument in the Rspec hooks., eg: `before(:each)` or `after(:each)`
- [RSpec/ContextWording](https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/ContextWording): We are using `given ...` term in most of our test
The rubocop-rspec is load

Adding rubocop-rspec

---

.template/variants/web/spec/support/assets.rb

Prepare webpack assets only if there is at least one system test is executed, solve https://github.com/nimblehq/rails-templates/issues/205
Just change to use when_first_matching_example_defined config
Run normal tests (not type: :system) faster without webpack compilation
The webpack compilation should be run once before running system tests

Only run asset precompile on system test

---

.template/spec/base/config/environments/production_spec.rb
config/environments/production.rb

Solve https://github.com/nimblehq/rails-templates/issues/234
Allow Rails server static by default as by default we don't have the Web server by default (like Nginx, Apache,..)
This configuration could be disabled on the [Nginx addon PR](https://github.com/nimblehq/rails-templates/pull/232)
The test should be passed

Allow Rails serve static files as default

---

Gemfile.tt

I tried to assert template in my Internal Certification. For example in this code
```ruby
describe "GET new" do 
it "renders the new view" do 
get :new
expect(response).to render_template(:new)
end
end
```
I got an error
So `rails-controller-testing` allow us to use `assigns` and `assert_template`.
- Add `rails-controller-testing` to Gemfile template
Note : @hoangmirs concern is if there is another alternative or not because the last release of this lib was 4 years ago.
- Test case above is passed

Add rails-controller-testing to Gemfile template

---

.github/ISSUE_TEMPLATE/bug_template.md
.github/ISSUE_TEMPLATE/feature_template.md

Added the GitHub issue template.
Used the same template as our git-template - https://github.com/nimblehq/git-template/tree/master/.github/ISSUE_TEMPLATE 
- New Issue
- Bug Report
- Feature

Add github issue templates

---

.semaphore.yml
Dangerfile
Gemfile.tt
spec/support/simplecov.rb

Added [danger-undercover](https://github.com/nimblehq/danger-undercover) plugin to show missing test coverage in new changes in PRs with [undercover](https://github.com/grodowski/undercover)
As mentioned in this [comment](https://github.com/nimblehq/rails-templates/issues/221#issuecomment-690124978) in the PR: https://github.com/nimblehq/rails-templates/issues/221 we want to show a report about missing test coverages in new changes with `undercover` in PRs using `Danger`.
**Used in our internal project -**
- No Changes
- Changes in new commits

Add danger plugin danger-undercover

---

.semaphore/semaphore.yml
Gemfile.tt
README.md

Upgrade Rails to v6.1 - the latest stable version
Remove the version constraint for the [paranoia](https://github.com/rubysherpas/paranoia) gem: we had to explicitly set it to v2.4.2 when upgrading Rails to v6.0.1 in #116 because the previous versions don't work with Rails 6.
But for now, the latest version ([v2.4.3](https://github.com/rubysherpas/paranoia/releases/tag/2.4.3)) supports Rails 6.1.0 already so that constraint isn't necessary anymore:

Update Rails to the latest stable version 6.1.0

---

config/initializers/backtrace_silencers.rb

Solve https://github.com/nimblehq/rails-templates/issues/264
Just change the string to be replaced
Create a new project from the template and `config/initializers/backtrace_silencers.rb` has been changed

Fix: backtrace_silencers modification does not work on the latest rails version

---

.template/variants/web/template.rb

Correct the code to remove Turbolink from `application.js` since it doesn't work.
We don't use [Turbolink](https://github.com/turbolinks/turbolinks) so we remove it when initializing a new project using Rails-template. `app/javascript/packs/application.js` is one of the files we must make the change. We do that in `.template/variants/web/template.rb`:
https://github.com/nimblehq/rails-templates/blob/e077e6726e44411d0dfccbf93c7b1beaf546c769/.template/variants/web/template.rb#L44-L51
which expects the `application.js` has the following line of code to remove
```javascript
require("turbolinks").start()
```
but it is no longer the case. The code in the file is now:
making the removal code no longer work. Since Turbolink isn't removed, it results in failed (test image) Docker build 
This PR …

Correct the Turbolink removal for application.js

---

.template/addons/docker/docker-compose.test.yml.tt
.template/addons/nginx/bin/inject_port_into_nginx.sh
.template/addons/nginx/bin/start.sh
.template/addons/nginx/bin/template.rb
.template/spec/addons/base/nginx/template_spec.rb
Makefile

Bring the `test template` back
It happens since we merge the #274, we need to inject the $PORT into the Nginx configuration before running the test
1/ Before - The test template spec is not executed
2/ After - The test template spec is executed

Test doesn't run due to the NGINX configuration

---

.template/spec/variants/web/app/template_spec.rb

Rename variables.scss to _variables.scss
As per our convention - https://nimblehq.co/compass/development/code-conventions/css/#files
As the file `variables.scss` is imported in `application.scss` it should be renamed to `_variables.scss`

Rename variables.scss to _variables.scss

---

.template/variants/web/spec/support/disable_animation.rb

Error in system tests while matching HTML content in `disable_animation.rb`
In the previous implementation system tests were not running because of wrong matching -
After the change, it works as expected.
System tests running seamlessly in our internal project -

Fix html content matching bug

---

.template/variants/web/spec/support/capybara.rb

Fix an issue that the system tests when running inside Docker or Github action failed with this error `Net::ReadTimeout`.
We saw many failed system tests in the CX project when running on Github action or run the tests inside Docker with this error `Net::ReadTimeout`.
After trying different approaches, we found that adding that argument to capybara fixed it.
```
options.add_argument('disable-gpu')
```
I think something went wrong with the recent Chrome releases but don't know exactly the reason. Besides that, many tutorials of setting capybara on the internet also have that option added so we tried that and it fixed the issue.
https://thoughtbot.com/blog/headless-feature-specs-with-chrome#capybara-configuration
After this fix was made, the system tests works again in CX.

Fix failed system tests with the error Net::ReadTimeout

---

.reek.yml

Update Reek's configuration to make it's Rails-friendly when using engines
[Reeks' official documentation](https://github.com/troessner/reek#working-with-rails) recommend to add this to its configuration when working with Rails:
```yml
directories:
"app/controllers":
IrresponsibleModule:
enabled: false
NestedIterators:
max_allowed_nesting: 2
UnusedPrivateMethod:
enabled: false
InstanceVariableAssumption:
enabled: false
"app/helpers":
IrresponsibleModule:
enabled: false
UtilityFunction:
enabled: false
"app/mailers":
InstanceVariableAssumption:
enabled: false
"app/models":
InstanceVariableAssumption:
enabled: false
```
This PR adds a missing config for models and also support Rails engines
N/A

Update Reek config to make it's Rails-friendly when using engines

---

Gemfile.tt
README.md

Update Rails to the latest stable version v6.1.3.1 to avoid the issue of failing to start because of yanked dependency.
Rails depends on the [MimeMagic](https://github.com/mimemagicrb/mimemagic) gem (ActionMailbox -> ActiveStorage -> Marcel -> Mimemagic). But that gem recently yanked all v0.3.x versions, making the new Rails apps fail to start and the old ones fail to rebuild. Mimemagic also released new versions but changed the Licence from MIT -> GPL2 which isn't compatible with Rails' license anymore. 
Rails release a new version v6.1.3.1 to solve that issue by removing Mimemagic dependency.
- https://github.com/rails/rails/issues/41750
- https://github.com/rails/rails/releases/tag/v6.1.3.1
-  https://github.com/rails/marcel/releases/tag/v1.0.0
Nimble CX after upgrading to this version …

Update Rails to v6.1.3.1

---

.template/spec/variants/web/app/template_spec.rb
.template/spec/variants/web/package_json_spec.rb
.template/spec/variants/web/template_spec.rb
.template/variants/web/package.json.rb
.template/variants/web/template.rb

Set up TypeScript (TS) via Webpacker. I also updated the library `i18n-js` as it was preventing the TS set up to work properly. 
As part of the engineering roadmap for 2021, TypeScript is made default for Web projects. Learn more about the decisio on [Notion](https://www.notion.so/nimblehq/Make-TypeScript-default-in-Rails-Template-c40989f8884e48c5bb871912bd0a3c13)) and in [this retrospective presentation](https://docs.google.com/presentation/d/1wRFVS-TXYXacLLjAoyShz1F-Z6lkYrRMl2hgCM9PfTg/edit?usp=sharing).
TypeScript is installed when using the template:
When using the default pack tag:

Set up TypeScript by default

---

Gemfile.tt

- #295 
Replace paranoia gem with discard gem as default soft-delete gem.
Voted in #295 
Simple replace in GemFile.tt

[#295] RFC: Soft delete gem - paranoia or discard

---

.template/addons/github/.github/workflows/test.yml.tt

#299 
Added 1 step at the end of the `test` GitHub Action.
This will be triggered only if the tests failed.
It will upload the screenshots made by Rspec into the GitHub Actions artefacts.
```yml
- name: Upload system tests screenshots artifact
uses: actions/upload-artifact@v2
if: ${{ failure() }}
with:
name: system_tests_screenshots
path: tmp/screenshots/*
```
Code already in used by Elixir Template (cf #299 description).
I have published a fresh project generated from this branch.
Github actions have been configured and you can see [the screenshot uploaded here](https://github.com/malparty/rails_template_test_screenshot/actions/runs/1078143017):
The generated test.yml includes the step:

#299 Add system tests Screenshot upload to GitHub Actions

---

.template/variants/web/spec/support/disable_animation.rb

- #297 
- Add missing safe navigation operator in `spec/support/disable_annimation.rb` for web variant
Change is minimal, steps to reproduce the issue (and so to test) are described in #297 
I've implemented this change in my IC [here](https://github.com/malparty/google-search-ruby/pull/72/files) and it works perfectly.
`N/A`

#297 Fix: spec/support/disable_annimation.rb nil error for WebSocket requests

---

.template/addons/github/.github/PULL_REQUEST_TEMPLATE/RELEASE_TEMPLATE.md
.template/addons/github/.github/workflows/README.md.tt
README.md.tt

Add the Github template for the release pull requests that match our [convention](https://nimblehq.co/compass/development/version-control/release-management/#release-pull-request).
The implementation is identical with https://github.com/nimblehq/git-template/pull/15. 
Github supports multiple [templates for issues and pull requests](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates). For example, to define multiple pull request templates, simply define them like this:
```bash
.github
└── PULL_REQUEST_TEMPLATE
├── normal_template.md
└── release_template.md
```
But unlike issue templates - when opening a new issue, Github will show a template selection menu:
even with multiple pull request templates …

Add the release Pull request template

---

.github/PULL_REQUEST_TEMPLATE.md
.template/addons/github/.github/PULL_REQUEST_TEMPLATE.md

Applied the [new PR templates](https://github.com/nimblehq/git-template/pull/27) for both the template PR and the generated project PR.
`N/A`
| template PR | generated project PR |
|---|---|
|![image](https://user-images.githubusercontent.com/77609814/177969868-578bc9ef-25a2-4363-92ab-972b6e2cb5cc.png)|![image](https://user-images.githubusercontent.com/77609814/177969254-c3228d26-cd6f-44ce-ad29-3f85ea22f347.png)|

[#340] Update Git Template for Pull Request

---

.template/addons/docker/docker-compose.dev.yml.tt
.template/addons/docker/docker-compose.test.yml.tt
config/application.yml.tt
config/database.yml
template.rb

- Close #337 
Update PostgreSQL version from `12.1` to `14.4`
| `envsetup` working | Container is the right version |
|---|---|
| <img width="445" alt="image" src="https://user-images.githubusercontent.com/77609814/177118798-492875d7-48fb-4ff5-9dfd-25fd86335f56.png"> | <img width="464" alt="image" src="https://user-images.githubusercontent.com/77609814/177123524-40287c27-8f6a-4024-8db8-3367682b40a8.png"> |
| Db migration working | Using the application working |
|---|---|
| <img width="440" alt="image" src="https://user-images.githubusercontent.com/77609814/177124036-5a828aeb-f5af-46f4-8796-f998c8d252ae.png"> | <img width="948" alt="image" src="https://user-images.githubusercontent.com/77609814/177124575-75b6b075-a114-45fd-91b8-51a21540562a.png"> |

[#337] Update PostgreSQL version from 12 to 14

---

template.rb

#334 
[Yn] default is Yes, [yN] default is No. Generally in CLI prompt capital letter means default value.
**Old Behavior**
**New Behavior**

fix(#334): default install_addon_prompt? to No

---

.template/addons/hotwire/Gemfile.rb
.template/addons/hotwire/template.rb
.template/spec/addons/variants/web/hotwire/gemfile_spec.rb
.template/variants/web/template.rb
Makefile
template.rb

- Close #344 
- Add missing frozen string literals
- Run rubocop auto fix (warning it tries to add an `attr_reader` in an unwanted place!)
- Move the prompt for Hotwire with the other "Web Varient Prompts"
- Add the tests for the Hotwire add-ons
> ⚠️ When a forked branch PR is submitted, the checks will not run by default and needs to be run manually by a repository owner (after ensuring the GitHub Actions are not corrupted). This is the reason why this PR has been made, to fix issues that we were not aware on a previous external PR.
All tests now pass! ✅ 
It prompts for Hotwire AFTER the global prompts.

[#344] Fix: Test failing since the Hotwire feature

---

.template/addons/docker/docker-compose.yml.tt
template.rb

- Close #338 
Update Redis. 
Version 6.2 to ensure AWS compatibility. 
Patch 7 is the latest one.
...resulting in the following containers:

[#338] Update Redis version from 5.0.7 to 6.2.7

---

.template/addons/semaphore/.semaphore/semaphore.yml.tt
README.md
config/initializers/backtrace_silencers.rb

- Close #349 
This PR only handles the reference renaming. The real rename of the branch will be done at the time of the release.
Some workflow had both references to master and main so I kept both. For workflows that had only `master`, I changed them to `main` (as for example I cannot test the Circle CI pipeline at the moment, so I don't want to introduce a bug by adding some logic like `master || main`). 
Rails repository also renamed its branches, that is the reason why their is 1 renaming on the rails repository URL too 😇 
Simple renaming so the `files changed` section is the best! ;-)

[#349] Rename master to main

---

.github/workflows/test_variants.yml
.template/variants/web/spec/support/capybara.rb
Makefile

- Close #352 
- Remove the deprecated desired_capabilities from the capybara config
The `desired_capabilities` was deprecated quite some time ago and ended up being removed from the newer versions of our dependencies. 
We did not find another place to configure the logs (`ALL` everywhere). But we believe such a configuration is not a must-have and we can do without it. Feel free to challenge and suggest improvements! :) 
| Before | After |
|---|---|
|![image](https://user-images.githubusercontent.com/77609814/184325510-04f4b963-389a-4da3-98a7-b5bc26597c8d.png)|![image](https://user-images.githubusercontent.com/77609814/184325566-3acfbb0b-f270-4299-b457-d6f9c104a233.png)|
|![image](https://user-images.githubusercontent.com/77609814/184325471-42989e92-bcff-48bf-a14e-dedf9c24b280.png)|![image …

[#352] Fix: `ArgumentError: unknown keyword: :desired_capabilities` when running system tests with the headless_chrome driver

---

.github/workflows/test_variants.yml
Makefile
bin/docker-assets-precompile

- Close #191
Add the DATABASE_URL variable in the docker-assets-precompile script
All insights are discussed in the issue (#191)
All credits to Hoang for finding a clean fix!!
Tested on the EWA-Payroll project (as we already have the CI set up)
| Before | After |
|---|---|
| ![image](https://user-images.githubusercontent.com/77609814/184322448-33324a58-29b7-403e-9379-288b90af0288.png) | ![image](https://user-images.githubusercontent.com/77609814/184322403-db61413a-9552-4a38-b6b1-c795d6f9d61c.png) |
| ![image](https://user-images.githubusercontent.com/77609814/184321731-e51f1d86-4121-49b3-8079-6dfadcd53cb8.png) | ![image](https://user-images.githubusercontent.com/77609814/184322344-62a58ed0-81b6-4430-84d7-c6d70e11518a.png) |

[#191] Add a default database adapter for production environment

---

.template/variants/web/app/assets/stylesheets/functions/_sizing.scss

https://github.com/nimblehq/rails-templates/issues/366
Small update on the sizing function, using `calc` to remove deprecate warning from [Dart SASS](https://github.com/sass/dart-sass/) about [using the `/` for division](https://sass-lang.com/documentation/breaking-changes/slash-div)
N/A
After applying the change the warning gone
https://user-images.githubusercontent.com/1772999/193492716-f9abedae-ce2f-4557-a50a-289aa4526c41.mov

[#366] Update the sizing function to solve the deprecation warning on using `/` for division

---

.template/spec/variants/web/package_json_spec.rb
.template/variants/web/.stylelintrc
.template/variants/web/package.json.rb

- Close #365 
- Remove the custom config dependencies
- Add the Nimble Stylelint config dependency for Web Variant
- Use the Nimble config in the StyleLint
I also removed the version for the ESLint Config because its our internal package and we should get the latest version for any new project 🤔 
Tested in a fresh new project:

[#365] Use the @nimblehq/stylelint-config-nimble stylelint config

---

.reek.yml

- Close #363 
Just disabled that check :) 
Reason: We do not always have a pair of safe() and (un)safe!() method in our code. 
Example: `authorized!` is often used in controllers as per our conventions but we do not have the safe `authorize` equivalent.
`n/a`
Tested in our internal projects, we do not have this spam anymore! 👍 
| Before | After |
|---|---|
|![image](https://user-images.githubusercontent.com/77609814/195786941-d2204611-c430-4c61-8854-1a21816fc358.png)|![image](https://user-images.githubusercontent.com/77609814/195787532-5929a5b0-e2ba-423e-a406-138bfcff3db9.png)|

[#363] Fix: Remove the "Has missing safe method" check from the Danger code review

---

.template/variants/web/app/javascript/build.js

- close #380
Fix esbuild watch implementation for v0.17.*
> **Note** I'm not "locking" the package.json to a specific version of `esbuild` as I believe it is better to be aware of these errors while working on long-term improvement of the template, rather than realizing that a client project was scaffolded with outdated versions.
Test are passing ✅ 
| js.1 | web.1 | 
|---|---|
|<img width="584" alt="image" src="https://user-images.githubusercontent.com/77609814/216885149-fd831bbf-4f51-4ae1-9bdb-968e8d3f0faa.png">|<img width="495" alt="image" src="https://user-images.githubusercontent.com/77609814/216885112-1a039b3c-c2ba-4eda-bec7-772a02976412.png">|
The console has no error, stimulus is well compiled and running as expected:
I also tested:
- While watch, edit the controller, the build is …

[#380] Fix: esbuild 0.17.X has different interface to implement the watch argument

---

.rubocop.yml

- Close #362 
Add 2 Rubocop rules to allow 10 expectations per spec and 5 nested blocks.
`n/a`
Quite straightforward. Tested in our current project. 😇

[#362] Fix: Rubocop prevent multi except tests

---

.github/CODEOWNERS
.github/workflows/test_production_build.yml
.github/workflows/test_template.yml
.github/workflows/test_variants.yml
.template/addons/github/.github/workflows/deploy_heroku.yml.tt
.template/addons/github/.github/workflows/test.yml.tt
.template/addons/github/.github/workflows/test_production_build.yml.tt
README.md.tt

- close #372 
Replace ::set-output with >> $GITHUB_OUTPUT and update actions
We can now use the `nimblehq/branch-tag-action@1` (instead of `@1.3.0`) thanks to a major version tag added, that will be maintained with each minor version increment.

[#372] Chore: Update deprecated set-output with GITHUB_OUTPUT environment file

---

.template/addons/github/.github/workflows/test.yml.tt

- close #376 
Run the lint job in a separated job so that we can get an early feedback when lint fail.
`n/a`

[gh376] Separate the linting job

---

.template/addons/bootstrap/package.json.rb
.template/addons/bootstrap/stylesheets/vendor/_bootstrap.scss

- close #389
Update bootstrap 5.1.3 to 5.2.3
Added import guidances in comments following the [Bootstrap documentation](https://getbootstrap.com/docs/5.2/migration/#new-_mapsscss).
_Example provided with margins, form-control and buttons_

[#389] Update Bootstrap 5.1.3 to 5.2.3 to resolve deprecated issues

---

.github/workflows/test_generated_app.yml
.github/workflows/test_production_build.yml
.github/workflows/test_template.yml
.template/addons/github/.github/workflows/deploy_heroku.yml.tt
.template/addons/github/.github/workflows/test.yml.tt
.template/addons/github/.github/workflows/test_production_build.yml.tt

- Close #378
- Remove `cancel-workflow-action` in all GitHub Actions workflows
- Use `concurrency` attributes in workflows to ensure only one job is run for each workflow 
We use `${{ github.workflow }}-${{ github.ref }}` for the group, which means separating it based on the `workflow` and the `ref`.

[#378] Feature: Convert `cancel-workflow-action` to native `concurrency`

---

bin/docker-assets-precompile
config/application.yml.tt

Solve the bug on `export the I18n locale for Javascript`
- The I18n JS task needs the AVAILABLE_LOCALES information to translate all contents
- We do not override the value, instead we just use the original value from the `application.yml`
Tested on client projects

Do not override the ENV value on Docker build stage

---

Gemfile.tt

close #404 
We're currently failing to generate the project from our template, both API and Web. It might be caused by some dependencies added to the existing gems. 
- I tried to roll back to some old commits, but still faced the same errors -> the root cause not related to recent changes ❌ 
- I tried to add `gem 'sassc'` into the Gemfile (before `bootsnap`) -> it works ✅ 
- I tried to add `gem 'sassc'` after it (in the assets group) -> it works locally to generate the project BUT failed to run the CI ❌ 
Generate the project successfully locally.

[#404] Fix: Loaderror: cannot load such file -- sassc when generating the project from the template

---

.template/spec/variants/web/package_json_spec.rb
.template/variants/web/Procfile.dev.rb
.template/variants/web/app/javascript/build.js
.template/variants/web/package.json.rb

close #385 
We customize the build process between development and `production`, as we want the `production` build to be as minimal as possible.
With JS, we config the `esbuild` configuration:
- Add `minify` option to be true in the case we don't have the `--watch` option (production)
With CSS, we separate two scripts:
- `build:css` for the production that included the `'--style=compressed'` option.
- `build:css-dev` for the `development` environment, without the compressed option.
| Minify JS                                                                                                                                                        	| Minify CSS …

[gh385] Minify the CSS and JS for production build

---

.template/addons/bootstrap/package.json.rb
.template/addons/bootstrap/stylesheets/vendor/_bootstrap.scss
.template/addons/phrase/spec/codebase/codebase_spec.rb
.template/variants/web/app/javascript/global.js
.template/variants/web/package.json.rb
.tool-versions
Gemfile.tt
README.md
spec/codebase/codebase_spec.rb
template.rb

close #383
Upgrade Node and Ruby dependency versions
- Still stay as Node 16, there is a [new issue for Node 18](https://github.com/nimblehq/rails-templates/issues/421)
- I changed to use the new `npm pkg set` syntax over the `npm set-script` ([Slack message](https://nimble-co.slack.com/archives/C01GL6RBW11/p1688357829582519)) on this PR too
The CI is passed

[#383] Upgrade Node and Ruby dependency versions

---

Gemfile.tt

close #416
Removed the sassc gem
I tried on local following the `Steps to reproduce` on https://github.com/nimblehq/rails-templates/issues/404 with
- Ruby 3.2.2
- Rails 7.0.6
- Without any addon
The project could be generated without any error
No error on the `rails  importmap:install` or `rails  turbo:install stimulus:install` step

[#416] Remove sassc

---

.template/spec/variants/web/package_json_spec.rb
.template/variants/web/.gitignore.rb
.template/variants/web/Procfile.dev.rb
.template/variants/web/app/javascript/build.js
.template/variants/web/app/template.rb
.template/variants/web/package.json.rb

Correct the `yarn task` for `build:css` as the `build:css-production` won't be trigger by any party, 
1. The [css-bundling](https://github.com/rails/cssbundling-rails/blob/main/lib/tasks/cssbundling/build.rake#L20) calls the `build:css` not `build:css-production` in the asset:precompile, see https://github.com/nimblehq/rails-templates/pull/405#discussion_r1251536103
2. For the `build:css-dev` we will use it in the `Procfile.dev`
The CI is passed

Correct the build:css task

---

.template/addons/bootstrap/stylesheets/vendor/_bootstrap.scss

close #393
Update the Bootstrap vendor file on Bootstrap 5.3
This is follow the [guide on the Bootstrap 5.3](https://getbootstrap.com/docs/5.3/customize/sass/#importing) with some modifier, we already used this in our projects without any error.
On the file changes tab

[#393] Update the Bootstrap vendor file

---

.template/variants/web/package.json.rb

close #414
- Enable source map when running css production build `yarn build:css`
- Generate source map with absolute path

Enable source-map option in CSS build

---

.template/addons/github/.github/workflows/publish_wiki.yml.tt

close #436
- Fix invalid workflow file bug for publish wiki workflow.
- `with` section wasn't getting access to `secrets` context.
```
with:
USER_NAME: github-wiki-workflow
USER_EMAIL: ${{ secrets.GH_EMAIL }}
secrets:
USER_TOKEN: ${{ secrets.GH_TOKEN }}
```
- As suggested in this [RFC](https://github.com/nimblehq/compass/discussions/1019), used this new [action](https://github.com/nimblehq/publish-github-wiki-action) to handle wiki publish.
https://github.com/mosharaf13/rails-template-wiki/actions/runs/5485979793

[#436] Fix invalid workflow bug for publish wiki workflow

---

.template/addons/github/.github/workflows/test.yml.tt
Dangerfile

close #223
- Skip danger run if PR has `[WIP]` in it's title
- Skip danger run if PR has `wip` in it's label
- Skip danger run if PR is in `draft`
- Tested on a project created from rails template. Worked successfully.

[#223] Ignore Danger run on WIP pull request

---

Dangerfile

close #448 
Having the following error using `brakeman.run` in Dangerfile causing error on CI.
```
danger-brakeman_scanner-0.1.1/lib/danger_plugin.rb:18:in `dirname':  (Danger::DSLError)
[!] Invalid `Dangerfile` file: no implicit conversion of nil into String
>  brakeman.run
```
```
/danger-brakeman_scanner-0.1.1/lib/danger_plugin.rb:18:in `dirname': no implicit conversion of nil into String (TypeError)
def run(options = File.dirname(Kernel.caller_locations.first.absolute_path))
```
I try to run with `brakeman.run('.')` and `brakeman.run('/.')`. Both are working fine. 
This is the test repo using our template only with `brakeman.run`. The CI is failing with the brakeman error. 
Here's the [Action](https://github.com/htoo-eain-lwin/hello/actions/runs/5678135724/job/15387975631) and here's …

[#448] Fix brakeman run raising error on CI.

---

.template/addons/github/.github/workflows/test.yml.tt
spec/rails_helper.rb

close #413 
Resolved the issue related to the code coverage always showing 0.00%, which means it does not reflect the real code coverage of the project. 
It was caused by the SimpleCov not starting before the Rails was loaded.
Tested and worked well on [the public repo](https://github.com/sanG-github/test-code-coverage/pull/1#issuecomment-1660059827)

[#413] The test coverage does NOT show the correct statistics

---

.template/variants/web/spec/support/capybara.rb

close #456 
Capybara tries to run the UI tests on different locale than our test suite causing a problem looking up some elements which contain localized string.
- Capybara should not inherit the page locale from the local web browser locale and instead always use English.
All tests passed.

[#456] Fix setting Chrome's locale to non-English will cause some Capybara tests to fail

---

.template/addons/github/.github/workflows/test.yml.tt

close #447 
We're providing some additional inputs that do not expect by the `download-artifact@v3` action.
Just removed the redundant inputs: `github_token, workflow, workflow_conclusion` as described. Keeps only the `name, path` inputs.
`n/a`

[#447] Remove unexpected_input being passed to actions/download-artifact@v3

---

config/sidekiq.yml

Add the queues with Rails env prefix in order to allow the Sidekiq job get processed.
The new default Rails generate had the `config.active_job.queue_name_prefix = Rails.env` which will require the Sidekiq queue to include these env prefixes.
Used in client projects

Update the sidekiq queue config

---

.gitattributes
.template/spec/base/template_spec.rb
template.rb

close #459
- Remove db/schema.rb from the git attributes auto-hidden files
- Add a test as well
`n/a`
After generating a new app named `man` (for `manger` in French, meaning `to eat` 🤡):

[#459] Remove schema.rb from .gitattributes linguist-generated

---

.template/addons/github/.github/workflows/deploy_heroku.yml.tt
.template/addons/github/.github/workflows/test.yml.tt
.template/addons/github/.github/workflows/test_production_build.yml.tt
.template/hooks/before_complete/fix_rubocop.rb
.template/spec/base/bin/template_spec.rb
.template/spec/variants/web/template_spec.rb
Makefile.tt
bin/template.rb
config/application.yml.tt

close #417
Improve the project generated by the template with the `--api` option, which is API application only. 
> [!NOTE]
> Due to the need for OpenAPI specs from `node` later, we no longer need to remove it.
- Removed all redundant parts as mentioned in the issue, thanks to @hoangnguyen92dn.
- Also change the deprecated `option` when running rubocop.
| Option before                                                                                                                          	| Option after                                                                                                                           	|
|---------------------------------------------------------------------------------------------------------------------------------------- …

[#417] Revise the config to generate the project for `--api` accordingly

---

.template/variants/web/.gitignore.rb
README.md.tt

After initializing a new project using the template, we need to copy the `.env.example` to `.env`. This enables the `Makefile` to work without any errors.
N/A
File changes

Update README regarding copying the .env file

---

.template/addons/docker/template.rb

close #478
Just remove the files before applying the Docker template. Later we might want to reverse that if we choose to use the default Rails docker files 👍 
`n/a`

[#478] Fix: Duplicated `Dockerfile` and `.dockerignore` when generating the project with Rails 7.1

---

.template/addons/docker/template.rb
.template/spec/base/config/application_spec.rb
Gemfile.tt
config/application.rb

close #109
Setup lograge and enable it in all environments.
`n/a`
|Gemfile|application config|
|---|---|
|![image](https://github.com/nimblehq/rails-templates/assets/77609814/7a57f7f2-dd2b-49ca-9ded-b2e4ce3f61a1)|![image](https://github.com/nimblehq/rails-templates/assets/77609814/da951bba-612d-43b7-9e0d-7b73cea683fe)|

[#109] Add lograge to tidy up logging when rendering actions

---

.github/ISSUE_TEMPLATE/bug_template.md
.github/ISSUE_TEMPLATE/chore_template.md
.github/ISSUE_TEMPLATE/feature_template.md
.github/PULL_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/release_template.md
.github/workflows/test_generated_app.yml
.github/workflows/test_production_build.yml
.template/addons/github/.github/workflows/test.yml.tt
.template/variants/web/.stylelintrc
.template/variants/web/app/assets/stylesheets/functions/_sizing.scss
.template/variants/web/package.json.rb
.tool-versions
Gemfile.tt
README.md
template.rb

close #489
It's faster to just update the needed dependencies rather than locking the template with outdated dependencies (with the cascading effect this can have).
- Rails 7.1.2
- Node 18.19
- Nimble Stylelint config 1.1.0 (required to lock `stylelint` to version 15 // version 16 raise an error)
Stylelint also came with new errors and I had to remove the global functions calls in favor of namespaced one.
The tests should now pass. No behavior changed. :white_check_mark:

[#489] Fix: Postcss not compatible with Node 16

---

.template/addons/github/.github/workflows/test.yml.tt

- Close #463
Update the `branch-tag` action to use the latest minor version, `branch-tag-action@1` instead of `branch-tag-action@v1.2`
`n/a`
Just a small update, nothing special as all the CI actions passed ✅

[#463] Update the branch-tag-action in the test workflow

---

.rubocop.yml
.template/addons/svgeez/helpers/svg_helper.rb

- Close #482
Enable the cop to enforce public methods YARD documentation.
`n/a`
The generated app passes the Rubocop check after adding the documentation to 1 public method (in the SVG helper):

[#482] Add the Rubocop cop to enforce YARD documentation for public methods

---

.template/addons/github/.github/workflows/test.yml.tt

- Close #429
Revised the test workflow, at the step using the `branch-tag-action` workflow.
Based on the current implementation of the branch-tag-action workflow, it should be `develop` instead of ~`development`~ since the `BRANCH_TAG` depends on the `branch` or `tag`.
```shell
if [[ $BRANCH_NAME == master || $BRANCH_NAME == main ]]
then
BRANCH_TAG=latest
elif [[ $TAG_NAME != $REF ]]
then
BRANCH_TAG=$TAG_NAME
else
BRANCH_TAG="${BRANCH_NAME//\//-}"
fi
```
`n/a`
Small change as described in the above section.

[#429] Revisit the test workflow

---

.rubocop.yml
.template/addons/custom_cops/template.rb
rubocop/custom_cops/class_template.rb
rubocop/custom_cops/class_template/expression_category.rb
rubocop/spec/class_template/expression_category_spec.rb
rubocop/spec/class_template_spec.rb
rubocop/spec/required_inverse_of_relations_spec.rb

- Close #499
Enforce class template with custom Rubocop rule
https://nimblehq.co/compass/development/code-conventions/ruby/#convention-40
The cop is divided into two phases:
1. Expression categorize phase: every expressions in the class body will classify into one of [these categories](https://github.com/nimblehq/rails-templates/pull/509/files#diff-0386f106cc4b680195ae1e3c9125582be517effb3a99d7260d3aa6aae6229eefR9-R23). If none matches, it'll be `:unknown`
2. Validate the order of the class body expressions according to the template
https://github.com/nimblehq/rails-templates/assets/35915460/fbdb2105-a9c5-4ef8-8e76-0b37ad120cfd
https://github.com/nimblehq/rails-templates/assets/35915460/02e996e5-ee7e-4b09-9861-29716144f434

[#499] Create a Rubocop cop for ordering instructions in class (e.g. Models)
